name: Manual Wyckoff Screener
on:
  workflow_dispatch:
    inputs:
      telegram_notification:
        description: 'Send Telegram notifications'
        required: false
        default: 'true'
        type: boolean
jobs:
  run-screener:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Create .env file
        run: |
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" > .env
          echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> .env
      
      - name: Run Wyckoff Screener
        run: python -m src.screener
      
      - name: Upload charts
        uses: actions/upload-artifact@v4
        with:
          name: breakout-charts
          path: charts/
          retention-days: 7
      
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: screening-results
          path: results/
          retention-days: 30
